apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-api
  labels:
    app: cms-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cms-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cms-api
    spec:
      containers:
        - name: cms-api
          image: eu.gcr.io/josefs-cms/cms-api-prod:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: uri
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/run/secret/cloud.google.com/firebase-service-account.json
          volumeMounts:
            - name: firebase-service-account
              mountPath: /var/run/secret/cloud.google.com
      volumes:
        - name: firebase-service-account
          secret:
            secretName: firebase-key
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: cms-api-hpa
  labels:
    app: cms-api
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cms-api
---
apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  name: cms-api-service
  labels:
    app: cms-api
spec:
  externalTrafficPolicy: Cluster
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: cms-api
  type: LoadBalancer
  loadBalancerIP: 35.195.191.106