apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-api
  labels:
    app: cms-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cms-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cms-api
    spec:
      containers:
        - name: cms-api
          image: eu.gcr.io/josefs-cms/cms-api-prod:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              #Make sure path matches exactly including trailing slash
              path: /api/
              port: 8080
          ports:
            - containerPort: 8080
            # sensitive env vars loaded using secrets
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: database
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: database
                  key: DB_PASS
            - name: FIREBASE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: firebase
                  key: api-key
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/run/secret/cloud.google.com/firebase-service-account.json
              # loads firebase credentials file from secrets
          volumeMounts:
            - name: firebase-service-account
              mountPath: /var/run/secret/cloud.google.com
      volumes:
        - name: firebase-service-account
          secret:
            secretName: firebase-key