
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cms-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: cms
  labels:
    app: cms
spec:
  backend:
    serviceName: cms-app-service
    servicePort: 80
  rules:
    - http:
        paths:
          - path: /api
            backend:
              serviceName: cms-api-service
              servicePort: 80
