# exposes deployment as network service
apiVersion: v1
kind: Service
metadata:
  name: cms-api-service
  labels:
    app: cms-api
spec:
  type: NodePort
  selector:
    app: cms-api
  ports:
    - port: 8080
      targetPort: 8080
